#include "ft_printf.h"

/*int		main()
{
	int d;
	unsigned int n;
	char *s;

	s = "heya";
	d = 42;
	n = -42;
	printf("%s-----------------MYPRINTF--------------%s\n", RED, END);
	printf("%sTEST FLAGS et D == POSITIF =>%s\n", GREEN, END);
	ft_printf("%0d\n", d);
	ft_printf("width 3 et flag 0: %03d\n", d);
	ft_printf("width 3 et flag - : %-3d\n", d);
	ft_printf("width 6 et flag - : %-6d\n", d);
	ft_printf("precision 3 : %.3d\n", d);
	ft_printf("flag - : %-d\n", d);
	ft_printf("flag - et precision 4: %-.4d\n", d);
	ft_printf("flag + : %+3d\n", d);
	ft_printf("flag + et width 5 : %+5d\n", d);
	ft_printf("flag + et width 1 : %+1d\n", d);
	ft_printf("flag + et precision 5 : %+.5d\n", d);
	ft_printf("flag 0 et precision 5 : %0.5d\n", d);
	ft_printf("flag 0 et precision 1 : %0.1d\n", d);
	ft_printf("flag + et precision 1 : %+.1d\n", d);
	ft_printf("flag 0 et width 5 : %05d\n", d);
	ft_printf("flag 0 et width 1 : %01d\n", d);
	ft_printf("flag esp et precision 4 : % .4d\n", d);
	ft_printf("flag esp et precision 1 : % .1d\n", d);
	ft_printf("flag esp et width 1 : % 1d\n", d);
	ft_printf("flag esp et flag - : % -d\n", d);
	ft_printf("flag esp et width 5 : % 5d\n", d);
	printf("%sTEST FLAGS et D == NEGATIF =>%s\n", RED, END);
	ft_printf("width 5 et flag 0: %05d\n", n);
	ft_printf("width 5 et flag - : %-5d\n", n);
	ft_printf("precision 3 : %.3d\n", n);
	ft_printf("flag - : %-d\n", n);
	ft_printf("flag - et precision 4: %-.4d\n", n);
	ft_printf("flag + : %+3d\n", n);
	ft_printf("flag + et width 5 : %+5d\n", n);
	ft_printf("flag + et width 1 : %+1d\n", n);
	ft_printf("flag + et precision 5 : %+.5d\n", n);
	ft_printf("flag 0 et precision 5 : %0.5d\n", n);
	ft_printf("flag 0 et precision 1 : %0.1d\n", n);
	ft_printf("flag + et precision 1 : %+.1d\n", n);*/
	/*printf("%s-----------------MYPRINTF--------------%s\n", RED, END);
	
	ft_printf("flag # et precision 5 : %#.5d\n", n);
	ft_printf("flag #  : %#d\n", n);
	ft_printf("flag + et precision 5 : %+.5d\n", n);
	ft_printf("flag + et precision 5 : %+.5d\n", n);
	ft_printf("flag + et precision 5 : %+.5d\n", n);
	ft_printf("flag + et precision 5 : %+.5d\n", n);
	ft_printf("flag + et precision 5 : %+.5d\n", n);
	ft_printf("flag + et precision 5 : %+.5d\n", n);
	ft_printf("flag - et width 5 : %-5d\n", n);
	ft_printf("flag - et width 3 : %-3d\n", n);
	ft_printf("flag 0 et width 5 : %05d\n", n);
	ft_printf("flag 0 et width 1 : %01d\n", n);
	ft_printf("flag 0 et width 1 : %01d\n", n);
	ft_printf("flag esp et precision 4 : %.4d\n", n);
	ft_printf("flag esp et precision 1 : %.1d\n", n);
	ft_printf("flag esp et width 1 : % 1d\n", n);
	ft_printf("flag esp et flag - : %-d\n", n);
	ft_printf("flag esp et width 5 : %5d\n", n);
	ft_printf("precision 3 et width 5 =%5.3d\n", n);
	ft_printf("precision 3 et width 5 =%5.3d\n", d);
	
	printf("%s-----------------PRINTF----------------%s\n", GREEN, END);
	printf("flag # : %x\n", n);
	printf("flag #  : %#d\n", n);
	printf("flag - et width 5 : %-5d\n", n);
	printf("flag - et width 3 : %-3d\n", n);
	printf("width 5 et flag 0: %05d\n", n);
	printf("width 5 et flag - : %-5d\n", n);
	printf("precision 3 : %.3d\n", n);
	printf("flag - : %-d\n", n);
	printf("flag - et precision 4: %-.4d\n", n);
	printf("flag + : %+3d\n", n);
	printf("flag + et width 5 : %+5d\n", n);
	printf("flag + et width 1 : %+1d\n", n);
	printf("flag + et precision 5 : %+.5d\n", n);
	printf("flag 0 et precision 5 : %0.5d\n", n);
	printf("flag 0 et precision 1 : %0.1d\n", n);
	printf("flag + et precision 1 : %+.1d\n", n);
	printf("flag 0 et width 5 : %05d\n", n);
	printf("flag 0 et width 1 : %01d\n", n);
	printf("flag esp et precision 4 : %.4d\n", n);
	printf("flag esp et precision 1 : %.1d\n", n);
	printf("flag esp et width 1 : % 1d\n", n);
	printf("flag esp et flag - : % -d\n", n);
	printf("flag esp et width 5 : %5d\n", n);
	printf("precision 3 et width 5 =%5.3d\n", n);
	printf("precision 3 et width 5 =%5.3d\n", d);
	printf("%sTEST D =>%s\n", GREEN, END);
	printf("%sTEST FLAGS et D == POSITIF =>%s\n", GREEN, END);
	ft_printf("flag 0 =%0d\n", n);
	printf("width 3 et flag 0: %03d\n", d);
	printf("width 3 et flag - : %-3d\n", d);
	printf("precision 3 : %.3d\n", d);
	printf("flag - : %-d\n", d);
	printf("flag - et precision 4: %-.4d\n", d);
	printf("flag + : %+3d\n", d);
	printf("flag + et width 5 : %+5d\n", d);
	printf("flag + et width 1 : %+1d\n", d);
	printf("flag + et precision 5 : %+.5d\n", d);
	printf("flag 0 et precision 5 : %0.5d\n", d);
	printf("flag 0 et precision 1 : %0.1d\n", d);
	printf("flag + et precision 1 : %+.1d\n", d);
	printf("flag 0 et width 5 : %05d\n", d);
	printf("flag 0 et width 1 : %01d\n", d);
	printf("flag esp et precision 4 : % .4d\n", d);
	printf("flag esp et precision 1 : % .1d\n", d);
	printf("flag esp et width 1 : % 1d\n", d);
	printf("flag esp et flag - : % -d\n", d);
	printf("flag esp et width 5 : % 5d\n", d);
	printf("%sTEST FLAGS et D == NEGATIF =>%s\n", RED, END);*/
	/*printf("width 5 et flag 0: %05d\n", n);
	printf("width 5 et flag - : %-5d\n", n);
	printf("precision 3 : %.3d\n", n);
	printf("flag - : %-d\n", n);
	printf("flag - et precision 4: %-.4d\n", n);
	printf("flag + : %+3d\n", n);
	printf("flag + et width 5 : %+5d\n", n);
	printf("flag + et width 1 : %+1d\n", n);
	printf("flag + et precision 5 : %+.5d\n", n);
	printf("flag 0 et precision 5 : %0.5d\n", n);
	printf("flag 0 et precision 1 : %0.1d\n", n);
	printf("flag + et precision 1 : %+.1d\n", n);
	printf("flag 0 et width 5 : %05d\n", n);
	printf("flag 0 et width 1 : %01d\n", n);
	printf("flag esp et precision 4 : %.4d\n", n);
	printf("flag esp et precision 1 : %.1d\n", n);
	printf("flag esp et width 1 : % 1d\n", n);
	printf("flag esp et flag - : % -d\n", n);
	printf("flag esp et width 5 : % 5d\n", n);
	printf("precision 3 et width 5 =%5.3d\n", n);
	printf("precision 3 et width 5 =%5.3d\n", d);
	printf("%s-----------------PRINTF----------------%s\n", GREEN, END);
	printf("%x\n", n);
	printf("%x\n", d);
	printf("flag #  : %#x\n", d);
	printf("flag # et width 6  : %#6x\n", d);
	printf("flag - et width 6  : %-6x\n", d);
	printf("flag  et width 6  : % 6x\n", d);
	printf("flag 0 et width 5 : %05x\n", d);
	printf("flag 0 et width 5 : %05X\n", d);
	printf("%x", d);
	printf("%x", d);
	printf("%x", d);
	printf("%x", d);
	printf("%x", d);
	printf("%x", d);
	printf("%x", d);
	printf("%x", d);
	printf("%x", d);
	printf("%x", d);
	printf("%x", d);
	return (0);
}*/

int		main()
{
	char				*s;
	unsigned int		nb;
	char c;
	
	s = "salut";
	c = 's';
	nb = 10;
	//printf("%s-----------------FT_PRINTF----------------%s\n", GREEN, END);
	//ft_printf("%10.10x\n", nb);
	//printf("%10.10x\n", nb);
	//ft_printf("%p\n", s);
	printf("%s-----------------PRINTF----------------%s\n", GREEN, END);
	printf("%p\n", s);
	printf("%s-----------------FT_PRINTF----------------%s\n", GREEN, END);
	ft_printf("%p\n", s);
	ft_printf("%10p\n", s);
	//ft_printf("%x\n", nb);
	//printf("%x\n", nb);
	//printf("%-100p\n", s);
	//printf("%100p\n", s);
	//printf("%x\n", c);
	/*ft_printf("%-10x\n", nb);
	ft_printf("%.10x\n", nb);
	ft_printf("%-.10x\n", nb);
	ft_printf("mine %#o\n", nb);
	ft_printf("mine %10o\n", nb);
	ft_printf("mine %-10o\n", nb);
	ft_printf("mine %-10o\n", nb);
	ft_printf("mine %-.10o\n", nb);
	ft_printf("mine %.10o\n", nb);
	printf("%s-----------------PRINTF----------------%s\n", RED, END);
	printf("%10c\n %c\n", c, c);
	printf("%-10c\n", c);
	printf("%c\n", c);
	printf("%.10c\n", c);
	printf("%#o\n", nb);
	printf("%10o\n", nb);
	printf("%-10o\n", nb);
	printf("%-10o\n", nb);
	printf("%-.10o\n", nb);
	printf("%.10o\n", nb);
	printf("mien = %s\n", ft_itoab_uintmax(nb, 16));
	printf("mien = %s\n", ft_itoab_uintmax(nb, 16));
	printf("vrai = %x\n", nb);
	printf("vrai = %5x\n", nb);
	printf("vrai = %15x\n", nb);
	printf("vrai = %.15x\n", nb);
	printf("vrai = %.10x\n", nb);
	printf("vrai = %0x\n", nb);
	printf("vrai = %0x\n", nb);
	printf("vrai = %#15x\n", nb);
	printf("vrai = %#.15x\n", nb);*/
	/*printf("%s-----------------MY_PRINTF----------------%s\n", GREEN, END);
	ft_printf("none = %x\n", nb);
	ft_printf("none upper = %X\n", nb);
	ft_printf("width 5 = %5x\n", nb);
	ft_printf("width 15 = %15x\n", nb);
	ft_printf(" precision 15 = %.15x\n", nb);
	ft_printf(" flag - et width 10 = %-10x\n", nb);
	ft_printf(" flag 0 = %0x\n", nb);
	ft_printf(" flag # et width 15 = %#15x\n", nb);
	ft_printf("mine = %#15X\n", nb);*/
	return (0);
}
